version: "3.8"
services:
  app:
    build: .
    container_name: hexagonal_fastify_boilerplate
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
